### ISSUE TITLE
Percentage of fully vaccinated people

### ISSUE THREAD

**Issue by MariosKef** [GreeceInFigures/greeceinfigures-data#1]
Congrats for the very nice initiative and website! Very helpful!

The percentage of fully vaccinated people on your website is 51% with data taken from data.gov.gr and the population size from 2020 eurostat. The ecdc states about 60% of fully vaccinated currently in Greece. Could it be that you need to divide _not_ by the total population but by the number of people above 18, for example?

Kudos for the website again! :100:

**Comment by dimichai** [comment]
Thank you @MariosKef!
ECDC indeed reports the percentage of vaccinated adults, but since 2 weeks ago under 18s started vaccinating as well.
The issue is that on the daily update from data.gov.gr the doses are not split by age, hence there is no way of knowing how many of those are adults.
ECDC provides this data but only updates it weekly, not daily.

**Comment by MariosKef** [comment]
@dimichai Thanks for your reply!
